### ISSUE TITLE
Not compatible with home.alias and home.hide_in_urls

### ISSUE THREAD

**Issue by jbouzekri** [getgrav/grav-plugin-feed#11]
I have a blog running on grav.

It has a page collection `blog` with articles inside.

So I configured it that way : 

``` yml
home:
  alias: '/blog'
  hide_in_urls: true
```

When I go to the rss feed page : `http://blog.local/blog.rss`, it generates a XML with the tag `channel/link` having this value : `http://blog.local.rss`.

It seems that it is removing the `/blog` because of my configuration.
