### ISSUE TITLE
Feed not loading after upgrading to 1.8.3

### ISSUE THREAD

**Issue by doryiii** [getgrav/grav-plugin-feed#62]
I don't recall what the last version was, but I recalled it was working back in Sep 2020.

After upgrading to grav 1.7.15 and feed 1.8.3, the feed URLs no longer works. Before, going to https://bakkin.moe/home.rss would load the RSS feed for the _home_ blog content; however, now it just brings up the actual blog HTML page.

No config has been changed since June 2020, including during the recent upgrade.

**Comment by rhukster** [comment]
Are you sure you are on Feed v1.8.3? That has a fix that specifically addresses the issue you are describing.

if so, then could I get a copy of your homepage .md file?  Perhaps it has a different configuration I'm not taking into account.  Cheers.

**Comment by doryiii** [comment]
Yes, I am running Feed v1.8.3
![image](https://user-images.githubusercontent.com/3710118/120423810-037fa980-c320-11eb-99ae-cde167aed959.png)

my user/pages/01.home/blog.md:
```
---
title: Home
visible: true
content:
    items: '@self.children'
    order:
        by: date
        dir: desc
    limit: 10
    pagination: true
    filter:
        visible: true
annewsment:
    items:
        -
            '@page.self': /annewsment
    filter:
        visible: true
---
```

**Comment by Sasumotu** [comment]
Got the same problem since 1.8.2. 1.8.3 also didn't fix it for me.

frontpage.md:

```yaml
---
title: Home
sitemap:
    changefreq: monthly
content:
    items: '@self.children'
    order:
        by: date
        dir: desc
    limit: 5
    pagination: true
feed:
    limit: 10
pagination: true
cache_enable: false
---
```
