### ISSUE TITLE
RSS and ATOM Links Reload Page Instead of Generating Feeds

### ISSUE THREAD

**Issue by thekenshow** [getgrav/grav-plugin-feed#76]
I have a Grav 1.7.45 site with the latest Quark theme and Feeds plugin enabled. The /news page (blog.md) page renders the expected items, per:

```
content:
    items:
        - '@self.children'
    leading: 0
    columns: 2
    limit: 10
    order:
        by: date
        dir: desc
    show_date: false
    pagination: true
    url_taxonomy_filters: true
 ```

When I click either the RSS or Atom links, the page simply refreshes and no feed is generated. Screen shots below:

News page:

![image](https://github.com/getgrav/grav-plugin-feed/assets/998832/316ba480-5a8a-49aa-b68c-d58c92787040)

Atom page:

![image](https://github.com/getgrav/grav-plugin-feed/assets/998832/d81e35fd-e053-499c-9c30-96e20e62063d)

RSS page:

![image](https://github.com/getgrav/grav-plugin-feed/assets/998832/73c9a54d-1c3b-4143-badf-2fc4a0fc747a)
